name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 ruff pytest pytest-cov

    - name: Run black check
      run: black --check .

    - name: Run isort check
      run: isort --check-only .

    - name: Run flake8 check
      run: flake8 .

    - name: Run ruff check
      run: ruff check .

    - name: Run tests with coverage
      run: pytest --cov=./ --cov-report=xml --cov-report=term

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
